//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QuaMFC.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDS_PROPSHT_CAPTION             103
#define IDD_PROP_CONFIG                 104
#define IDD_PROP_VST                    105
#define IDD_PROP_MIDI                   106
#define IDD_PROP_AUDIO                  107
#define IDR_HTML_TEST                   108
#define IDR_MAINFRAME                   128
#define IDR_QUAMFCTYPE                  129
#define ID_SHOW_CONTEXT_WIN             130
#define IDR_QUACONTEXTTYPE              130
#define IDB_BAKGND1_FULL                132
#define IDB_BAKGND1_256                 138
#define ID_WINDOW_QUACONTEXT            139
#define ID_TOOLS                        140
#define ID_EDIT                         141
#define ID_WINDOW_QUACONTEXT142         142
#define IDB_BUT_LG_U                    145
#define IDB_BUT_LG_O                    146
#define IDB_BUT_LG_D                    147
#define IDB_BUT_SM_D                    148
#define IDB_BUT_SM_O                    149
#define ID_SHOW_CONTEXT_WINDOW          150
#define IDB_BUT_SM_U                    150
#define IDB_BUT_SM_UE                   151
#define IDB_BUT_LG_E                    152
#define IDB_BUT_SM_OE                   153
#define IDB_BUT_SM_DE                   154
#define IDB_ROT_SM_K                    155
#define IDR_ARRANGER_TOOL               156
#define ID_VIEW_ARRANGERTOOLS           158
#define ID_VIEW_IDR                     159
#define IDB_BLAK_BLOK                   160
#define IDC_ARTOOL_REGION               162
#define IDC_ARTOOL_SLICE                163
#define IDC_ARTOOL_POINT                164
#define IDC_ARTOOL_DRAW                 165
#define IDB_SYM_IDX_IMG                 166
#define IDC_ARTOOL_DRAW_CTL             166
#define IDB_CLIP_LIST_IDX_IMG           167
#define IDC_ARTOOL_POINT_CTL            167
#define ID_DELETE_POPEDITOR             168
#define IDB_CLIP_IDX_IMG                169
#define ID_TEST_HISISA                  175
#define IDR_CHANNEL_RCLICK              176
#define ID_CHANNEL_EDITOR               177
#define ID_CHANNEL_CONTROLLER           178
#define ID_CHANNEL_DELETE               179
#define IDR_INSTANCE_RCLICK             191
#define ID_INSTANCE_CONTROLLER          192
#define ID_INSTANCE_DELETE              193
#define IDR_SCHEDULABLE_RCLICK          194
#define ID_SCHEDULABLE_EDITOR           195
#define ID_SCHEDULABLE_DELETE           196
#define IDR_VSTPLUGIN_RCLICK            197
#define ID_VSTPLUGIN_VIEW               198
#define ID_VSTPLUGIN_DISABLE            199
#define IDR_QUA_RCLICK                  200
#define ID_QUA_EDITOR                   201
#define IDR_PORT_RCLICK                 202
#define IDR_BUILTIN_RCLICK              203
#define IDR_TEMPLATE_RCLICK             204
#define IDB_TAKE_IDX_IMG                205
#define IDR_VSTPLUGIN_GLOBAL_RCLICK     205
#define ID_METHOD_EDITOR                206
#define ID_METHOD_DELETE                207
#define IDR_METHOD_RCLICK               208
#define IDB_QP_STATE_OK                 210
#define IDB_QP_STATE_ERR                211
#define IDB_QP_STATE_DEFER              212
#define IDB_CTXT_IDX_IMG                213
#define IDB_ICO_SM_MDI                  214
#define IDB_ICO_SM_AUD                  215
#define IDR_CLIP_RCLICK                 215
#define IDB_ICO_SM_JOY                  216
#define IDB_ICO_SM_CHAN                 217
#define IDB_ICO_SM_NON                  218
#define ID_STREAMTAKE                   218
#define IDB_ARROW_R_SM                  219
#define IDR_STREAMTAKE_CREATE           219
#define IDB_ARROW_L_SM                  220
#define ID_SAMPLETAKE                   220
#define IDB_CTXT_IDX_IMG1               221
#define IDB_SIMPLEVAR_IDX_IMG           221
#define IDB_CLSBUT_SM_D                 222
#define ID_CLIP                         223
#define IDB_CLSBUT_SM_O                 223
#define ID_CLIP_CREATE224               224
#define IDB_CLSBUT_SM_U                 224
#define IDB_BUT_MIN_SM_DE               225
#define IDB_BUT_MIN_SM_D                226
#define IDB_BUT_MIN_SM_OE               227
#define IDB_BUT_MIN_SM_O                228
#define IDB_BUT_MIN_SM_UE               229
#define IDB_BUT_SM_U1                   230
#define IDB_BUT_MIN_SM_U                230
#define IDB_BUT_BLANK_SM_DE             231
#define ID_Menu                         232
#define IDB_BUT_BLANK_SM_D              232
#define ID_EDIT_ADDMETHOD               233
#define IDB_BUT_BLANK_SM_OE             233
#define ID_ADDCHANNEL_STEREOIN          234
#define IDB_BUT_BLANK_SM_O              234
#define ID_Menu235                      235
#define IDB_BUT_BLANK_SM_UE             235
#define ID_ADDCHANNEL_MONOIN            236
#define IDB_BUT_BLANK_SM_U              236
#define ID_ADDCHANNEL_STEREOIN237       237
#define ID_STREAMTAKE_ADDCLIP           238
#define ID_SAMPLETAKE_ADDCLIP           239
#define IDD_PARSE_ERROR                 241
#define IDR_METHOD_TOP_RCLICK           243
#define ID_CHANNELTOP                   244
#define ID_CHANNELTOP_ADDCHANNEL        245
#define ID_Menu246                      246
#define ID_SAMPLETOP                    247
#define ID_VOICETOP                     248
#define ID_VOICETOP_ADDVOICE            249
#define ID_SAMPLETOP_ADDSAMPLE          250
#define ID_METHODTOP_ADDMETHOD          251
#define ID_Menu252                      252
#define ID_METHOD_ADDMETHOD             253
#define ID_CHANNEL_ADDMETHOD            254
#define ID_TOPLEVELREGION_ADDMARKER     255
#define ID_METHODTOP_ADDMARKER          256
#define ID_TOPLEVELREGION_SELECTREGION  257
#define ID_TOPLEVELREGION_GOTOSTARTOFREGION 258
#define ID_TOPLEVELREGION_SELECTREGION259 259
#define ID_TOPLEVELREGION_GOTOSTARTOFREGION260 260
#define ID_TOPLEVELREGION_GOTOMARK      261
#define ID_Menu262                      262
#define ID_TOPLEVELREGION_GOTOENDOFREGION 263
#define IDD_CC_DIALOG                   264
#define ID_EDIT_ADDCHANNEL              266
#define ID_VSTPLUGIN_GLOBAL_SAVE        300
#define ID_VSTPLUGIN_GLOBAL_RELOAD      301
#define ID_VSTPLUGIN_GLOBAL_SET_DIRECTORY 302
#define ID_VSTPLUGIN_GLOBAL_ADD_DIRECTORY 303
#define ID_CLIP_EDIT                    400
#define ID_CLIP_DELETE                  401
#define ID_CLIP_CREATE                  402
#define ID_TAKE_EDIT                    403
#define ID_TAKE_DELETE                  404
#define ID_TAKE_CREATE                  405
#define IDR_SAMPLETAKE_RCLICK           416
#define IDR_STREAMTAKE_RCLICK           417
#define ID_STREAMTAKE_CREATE            418
#define ID_STREAMTAKE_EDIT              419
#define ID_STREAMTAKE_DELETE            420
#define ID_SAMPLETAKE_CREATE            421
#define ID_SAMPLETAKE_DELETE            422
#define ID_SAMPLETAKE_EDIT              423
#define IDR_STREAMTAKENULL_RCLICK       425
#define ID_CLIPNULL_CREATECLIP          426
#define IDR_SAMPLETAKENULL_RCLICK       427
#define IDR_STREAM_EDITOR_CONTEXT       450
#define ID_STREAMEDITORCONTEXT_ADD_CONTROLLER 451
#define IDR_SAMPLE_TOP_RCLICK           451
#define IDR_CHANNEL_TOP_RCLICK          452
#define IDR_METHOD_TOP_RCLICK1          453
#define IDR_VOICE_TOP_RCLICK            453
#define IDR_MAINCLIP_RCLICK             454
#define IDR_MAINCLIP_TOP_RCLICK         455
#define IDR_MAINMARK_RCLICK             456
#define IDR_MAINMARK_TOP_RCLICK         457
#define ID_STREAMEDITORCONTEXT_ADD_PROGRAM 590
#define ID_STREAMEDITORCONTEXT_ADD_BEND 730
#define ID_STREAMEDITORCONTEXT_ADD_VALUE 731
#define ID_STREAMEDITORCONTEXT_ADD_SYSC 732
#define ID_STREAMEDITORCONTEXT_ADD_SYSX 733
#define ID_STREAMEDITORCONTEXT_DEL_PROGRAM 734
#define ID_STREAMEDITORCONTEXT_DEL_BEND 735
#define ID_STREAMEDITORCONTEXT_DEL_VALUE 736
#define ID_STREAMEDITORCONTEXT_DEL_SYSC 737
#define ID_STREAMEDITORCONTEXT_DEL_SYSX 738
#define ID_STREAMEDITORCONTEXT_DEL_CTRL 739
#define ID_STREAMEDITORCONTEXT_DEL_NOTE 740
#define ID_STREAMEDITORCONTEXT_CLEAR_CONTROLLER 741
#define ID_EDITORCONTEXT_ADD_CLIP       742
#define ID_EDITORCONTEXT_DEL_CLIP       743
#define ID_EDITORCONTEXT_ADD_MARKER     744
#define ID_EDITORCONTEXT_DEL_MARKER     745
#define ID_EDITORCONTEXT_SELECT_CLIP    746
#define ID_EDITORCONTEXT_GOTOSTART_CLIP 747
#define ID_EDITORCONTEXT_GOTOEND_CLIP   748
#define ID_STREAMEDITORCONTEXT_SET_PROGRAM 800
#define ID_STREAMEDITORCONTEXT_SET_BANK 930
#define ID_STREAMEDITORCONTEXT_SET_SUBBANK 1010
#define IDC_PARSE_ERR_TXT               1034
#define IDC_ADDSTREAMIN                 1035
#define IDC_CC_ADDSTREAMIN              1035
#define IDC_CC_ADDSTREAMOUT             1036
#define IDC_CC_ADDAUDIN                 1037
#define IDC_CC_ADDAUDOUT                1038
#define IDC_CC_INMODE                   1039
#define IDC_CC_OUTMODE                  1040
#define ID_STREAMEDITORCONTEXT_DUP_CONTROLLER 1140
#define ID_VARIABLECONTEXT_ADD_VAR      1500
#define ID_VARIABLECONTEXT_ADD_VAR_TYPE_RANGE 1599
#define ID_VARIABLECONTEXT_SET_VAR_TYPE 1600
#define ID_VARIABLECONTEXT_SET_VAR_TYPE_RANGE 1699
#define ID_VARIABLECONTEXT_DELETE_SELECTED 1700
#define ID_VARIABLECONTEXT_ADD_METHOD   1701
#define ID_VARIABLECONTEXT_NODISPLAY_SELECTED 1702
#define ID_VARIABLECONTEXT_CONTROL_SELECTED 1703
#define ID_VARIABLECONTEXT_DISPLAY_SELECTED 1704
#define ID_VARIABLECONTEXT_ENVELOPE_SELECTED 1706
#define ID_VARIABLECONTEXT_SET_LENGTH_SELECTED 1708
#define ID_ARTOOL_BASE                  2000
#define ID_ARTOOL_RGSELECT              2000
#define ID_ARTOOL_POINT                 2001
#define ID_ARTOOL_SLICE                 2002
#define ID_ARTOOL_DRAW                  2003
#define ID_ARTOOL_LAST_BUTTON           2003
#define ID_TRANSPORT_BASE               3000
#define ID_PLAY_BUTTON                  3000
#define ID_STOP_BUTTON                  3001
#define ID_PAUSE_BUTTON                 3002
#define ID_RECORD_BUTTON                3003
#define ID_FF_BUTTON                    3004
#define ID_REWIND_BUTTON                3005
#define ID_TRANSPORT_PLAYTIME           3006
#define ID_TRANSPORT_TEMPO              3007
#define ID_FULL_FORWARD_BUTTON          3008
#define ID_FULL_REWIND_BUTTON           3009
#define ID_CONTEXT_BASE                 4000
#define ID_CONNECT_BUTTON               4000
#define IDC_BUTTON_ASIO_CTL             4100
#define IDC_ASIO_DRIVER_SELECT          4101
#define IDC_LIST1                       4107
#define IDC_LIST2                       4108
#define ID_EDIT_ADD_SAMPLE              4150
#define ID_EDIT_ADD_VOICE               4151
#define ID_EDIT_ADD_CHANNEL             4152
#define ID_EDIT_ADD_CHANNEL_POPUP       4153
#define ID_EDIT_ADD_CHANNEL_POPPED      4154
#define ID_EDIT_ADD_CHANNEL_OK		    4155
#define ID_EDIT_ADD_CHANNEL_CANCEL      4156
#define ID_EDIT_ADD_METHOD              4161
#define ID_EDIT_ADD_CHILD_METHOD        4162
#define ID_EDIT_ADD_CLIP                4163
#define ID_EDIT_ADD_MARKER              4164
#define ID_EDIT_SHOW_ENVELOPE           4200
#define ID_HELP_DONTPANIC               32776
#define ID_FILE_PREFERENCES             32777
#define ID_BUTTON32801                  32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        267
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
