

enum {
	QUA_GO = 'quag',
	QUA_PAUSE = 'quap',
	QUA_RESET = 'quar',
	QUA_NEW = 'quan',
	QUA_LOAD = 'qual',
	QUA_SAVE = 'quax',
	QUA_SAVE_AS = 'quaz',
	QUA_SELECT = 'quas',
	QUA_RECORD = 'quak',
	QUA_CLOSE = 'quac',
	QUA_TIME = 'quat',
	QUA_PALETTE = 'quao',
	QUA_EDIT = 'qued',
	CTRL_BANG = 'bang',
	DISPLAY_STATUS = 'stat',
	PARAM_SET = 'pars',
	UPDATE_CONTROL_VAR = 'pard',
	SET_GRANULARITY = 'setg',
	SET_OFFSET = 'seto',
	SET_RATE = 'setr',
	SET_ENVELOPE = 'sete',
	SET_WINDOW = 'sete',
	ADD_ITEM = 'addi',
	DEL_ITEM = 'deli',
	DEL_OBJECT = 'delb',
	MOVE_OBJECT = 'mvob',
	COPY_OBJECT = 'cpob',
	ADD_SYMBOL = 'asym',
	REDISPLAY_OBJECT = 'cpob',
	RESIZE_OBJECT = 'rsob',
	ENABLE_PLACE = 'enpl',
	SET_SOURCE = 'ssrc',
	SET_DESTINATION = 'sdst',
	SET_DISPLAY_MODE = 'sdip',
	
	ADD_INSERT = 'ains',
	DEL_INSERT = 'dins'
};
